export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';


export const GET_ALL_TODOS = 'GET_ALL_TODOS';
export const GET_ALL_TODOS_ERROR = 'GET_ALL_TODOS_ERROR';

export const GET_USER_TODOS = 'GET_USER_TODOS';
export const GET_USER_TODOS_ERROR = 'GET_USER_TODOS_ERROR';

export const GET_USER_TODO_BY_ID = 'GET_USER_TODO_BY_ID';
export const GET_USER_TODO_BY_ID_ERROR = 'GET_USER_TODO_BY_ID';

export const UPDATE_TODO_BY_ID = 'UPDATE_TODO_BY_ID';
export const UPDATE_TODO_BY_ID_ERROR = 'UPDATE_TODO_BY_ID_ERROR';


export const DELETE_TODO_BY_ID_ERROR = 'DELETE_TODO_BY_ID_ERROR';

export const ADD_TODOS_SUCCESS = 'ADD_TODOS_SUCCESS';
export const ADD_TODOS_ERROR = 'ADD_TODOS_ERROR';


